#!/usr/bin/bash

# (C) NORCE Climate
# Tyge Løvset, Feb. 2020


__cleanup()
{
    if [ -f $FILE.tmp ]; then
      rm $FILE.tmp
      echo Removed temp file.
    fi
}

trap __cleanup EXIT


DEFAULT=.filelist
FILE=$DEFAULT.ncdu.gz
CREATE=0
IMPORT=0
HELP=0
POSITIONAL=()

while [[ $# -gt 0 ]]
do
  key="$1"
  case $key in
    -z|--gzfile)
    FILE="$2"
    shift # past argument
    shift # past value
    ;;
    -i|--import)
    IMPORT=1
    shift # past argument
    ;;
    -c|--create)
    CREATE=1
    shift # past argument
    ;;
    -C)
    CREATE=2
    shift # past argument
    ;;    
    -h|--help)
    HELP=1
    POSITIONAL+=("$1") # pass it through
    shift # past argument
    ;;    
    *)    # unknown option
    POSITIONAL+=("$1") # save it in an array for later
    shift # past argument
    ;;
  esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

if [ $HELP == 1 ]; then
   echo "`basename $0` [-c | -C | -i] [-z filelist.gz]"
   echo "  -i, --import               Import specified or default filelist if it exists"
   echo "  -c, --create               Create new filelist and quit"
   echo "  -C                         Create new filelist and import it"
   echo "  -z file, --gzfile file     Specify a gz filelist. Default .filelist.ncdu.gz"
   echo "  -h, --help                 This help"
   echo ""
   `dirname $0`/ncdu2 --help
elif [ $CREATE != 0 ]; then
   `dirname $0`/ncdu2 $1 -x -1 --exclude ./.snapshots -o- | gzip > $FILE.tmp
   if [ -f $FILE.tmp ]; then
     if [ $FILE == $DEFAULT.ncdu.gz ] && [ -f $FILE ]; then
       mv $FILE $DEFAULT.last.gz
     fi
     mv $FILE.tmp $FILE
     if [ $CREATE == 2 ]; then
       gzip -dc $FILE | `dirname $0`/ncdu2 -y -f-
     fi
   fi
elif [ $IMPORT == 1 ]; then
   if [ -f $FILE ]; then
     gzip -dc $FILE | `dirname $0`/ncdu2 -y -f-
   else
     echo "Could not read import file: $FILE"
   fi
else
   `dirname $0`/ncdu2 $*
fi
